### ISSUE TITLE
Deployment not Kubernetes 1.16 compatible

### ISSUE THREAD

**Issue by marsdalesa** [jenkins-x-charts/vault-operator#15]
Hi,

I'm unaware of what range of Kubernetes versions is intended to be supported, but in line with jenkins-x/jx issue [#5675](https://github.com/jenkins-x/jx/issues/5675) the [deployment.yml](https://github.com/jenkins-x-charts/vault-operator/blob/master/vault-operator/templates/deployment.yaml) apiVersion is incompatible with Kubernetes 1.16 and needs to be changed to `apps/v1` - obviously breaking support for clusters below 1.9.

**Comment by ankitm123** [comment]
Related to https://github.com/jenkins-x/jx/issues/6957
